### ISSUE TITLE
Travel Blog Sharing System

### ISSUE THREAD

**Issue by shuhuiwu823** [shuhuiwu823/ExploreChinaNow#5]
## Epic
Allow users to post their travel experiences blog, comment on others' posts, and share the links to different social media, like Facebook/Instagram.

## User Stories
- [x] story #5 As a user, I would like to editing my personal blog and post it to the community.
- [ ] story #5 As a user, I want to leave comments on others' posts.
- [ ] story #5 As a user, I would like to get a sharable link to allow me forward the content to other social media platforms.
